CREATE TABLE `products` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL UNIQUE,
	`creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB

CREATE TABLE `users` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL UNIQUE,
	`email` VARCHAR(50) NOT NULL UNIQUE,
	`password` VARCHAR(128) NOT NULL,
	`session` VARCHAR(128) NULL,
	`creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB

CREATE TABLE `categories` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(50) NOT NULL UNIQUE,
	`creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY (id)
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB

CREATE TABLE `users_prods` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`prod_id` INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (prod_id) REFERENCES products (id) ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB

CREATE TABLE `prod_cat` (
	`id` INT NOT NULL AUTO_INCREMENT,
	`prod_id` INT NOT NULL,
	`cat_id` INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (cat_id) REFERENCES categories (id) ON DELETE CASCADE,
	FOREIGN KEY (prod_id) REFERENCES products (id) ON DELETE CASCADE
)
COLLATE='utf8_general_ci'
ENGINE=InnoDB